apiVersion: v1
data:
    access_token: ENC[AES256_GCM,data:SiBw2vFlimH2UnCGFZLNTKpMMY5whtUW8onEa2av9gc0qppn3hR2wRXq3oDwPl2TfUQ4uwxLtUViekjKV4JStsXBA7oJTqKo1LDsd7qtBshEY8UNqTBqw4cwaye6sfHwAQ4fMLNtAM60OBzO2hAt8+MMdLjGflmxF85yianRQTodtoNzWv7we2RLz4Bx7/BCjtVapCdf0mIhQ9bNz8GhzyMKBI+kBQ9es64fAIG6oJBLb6c02BAboeDFtosiwKm5XK+BwPd65tGldyEH71ercSK9fHKRJv3qcMbgn1A6DFjRrrTrY9mEpvKbttU0/zZk6pK0mruN7nex9kL4O6NPRjspHRYXOK/xpKcnfC+JjnvPTNzXME+6AmSPF3RHFSIF5iGTKIwN2YmROKE/S47FSoHxmaBvPXncS+GYhSCdZDM+/wxgU4z/qtSSm5fD/42/M+F1j95JJ0cXqzm6muhCsqb8zfJDeP8Wi4rEDcW9vAKE1tAGRhyRZWX9fx1jJZ1KI2zs+eyYHSD6Pz1hUYlS4USGHW+AvD8k+kY3GHxWcAo0GSeLD+35/IWkvdVKxqqpnSxrp/wUbyIjHxfxmExlluO4bNpuOUlmEYmvgFC7cI50pcG89OMpo5dCsQX1j+KMzLQbY/L95uyU9UXumdrklwNamup8XFnda6hZupDAmDCgFV+KGn4L41bwduT1lSz6HX54gCMoEEcwyZxNxVkJr6RTxGPxZIjJhuxDeZp4U06Jfqs9nCmMFd9c1+v8CvPwdi6hCSshXAK2FB3sfEM8nN2aTZUYyBxqA/Em2n+/ogVZegSMg7956+iib3eisvMJ0hjHY+tbnF0EI7fpprxES4HdaQyFoIzcEaEGVrxWkasTuBXOb5pqyfUhEmwjTBhVvIWPqybaFrGizoUyNdZyPykIvp0CUfsDZV/mN3MjbS2Ei4Sj3HTUFTSK6wTxi4Z+tRPPfjRt6pqi61YKWT+SaN3E7ESkm6QPBB3ea7OmaWPDjJXs3x193PvrIRLIZ2j70VAKPl17fK++rme6MfbDX0xwgJN+ilD1Tug43gZcRs/XwwdT2IfswGCAs3xHuOLyjLvZm5vM3flFaIkExaWJbW4augh4UHyB/HzVni26aF8kMEoGVQMwcw79SPxZ1wfTPyT4nsh1N0JWrVq1ftl7YiB8xKkvKHrZFHSiUzAaMYjfklD3mF8m19ONTUfBYxz4E0saitWx91OIS2/NzUFQcHuEBaYzx0PF7WHsbcw6whVsHr7JhenmX8JgZeichQKxvRXrtdDq6PzxlYzz7RbKfjMKSSs=,iv:a0SDeZO8AuQC5Vrldmo9c+rcnjlB6ayIVGFon6wweVg=,tag:gEb1ZWE5VuxNB2Y3FB1SMw==,type:str]
    app_key: ENC[AES256_GCM,data:vz7C2+wDu7+xrY+LUIdu+7cSGfJkWju4LLnKRRqSH2U=,iv:IXQNEo6PWdpGGi5TIu81RWM26Lyr4MCg2s/qkr3eGKg=,tag:FB7ReIjihpeZMVisaTfq9Q==,type:str]
    db_password: ENC[AES256_GCM,data:1i8E2eYlc1JvktO+DAMN1UgxKWVE8sXlCdXU2dc1VM0=,iv:S3cltQsRzSL/Xi8XE2qRwcL+5W5yJEW+x+0LTCyiyuQ=,tag:qviTvxDLfdFrqqh8zWaWQg==,type:str]
    static_cron_token: ENC[AES256_GCM,data:6bRroMkznMICbl0hvTDSPbmQVD5AKiaQQUw2KVdKA8jArbBk+tvzM9vs2nzSn10=,iv:uENNW1KWyDe9ZJN/An3qUANNKvRm7ImRHxrWBumNS0Q=,tag:CtZFcn5vSUKJP2VrC2JxlQ==,type:str]
kind: Secret
metadata:
    name: firefly-secrets
    namespace: firefly
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wr3fcrdnazdx38df72fqe30r5af8yue54w7uzejw8gull8p2gefqsp2sh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVnl0djNQWW01OGFBY0Fq
            VkNHU2NQZ2dBbFlwalNrWmR3TSt3bHVFM1E4CmZ4Z2IrekhqS1BHenRLc3NCZS9k
            bkw5Tm1UN0NDbytPNTRGSDlpbmhxWXcKLS0tIDNmcXhYeHVCYUZTendQOGhBTW1z
            cGxHUkpEc3cyUjNsRUc3THJzbEhpdlUK7D6ANblZVqPylbs5pYRnsnvXQcp/H4ql
            HtwyoU4ecBYBVfupekEF0oFhBzONs+fu45uVgk13xJihy2OuwEqP6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-22T19:09:13Z"
    mac: ENC[AES256_GCM,data:rM72FewTkBEdOwCaJFEmjmIUToK/QIlTHMqywn0i8Yr4L08YogXlN3WKXaRz1C5kUS0Oev7lzhqyF7MRvRAxyriUo+c6NNtQxIsGRO3kf9gKxAaVNX6S6mqnncNV5wRKW2nMbJ+x5t/nUL8U+fR4W9H8jD/N3iwyuW7DXk6PWnk=,iv:kuMtceAkrGatWeUpEf3ia0DcoiUI4xAMte38YbCnzig=,tag:oUvIr2RemosPbqv4EN+kxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
