apiVersion: v1
data:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wa4AKKumX+NHtbP/,iv:3FkgzOPiSzClGCQkRM7fdaDDQ1nWXLfia/tTyYBLW/s=,tag:SoEKJRIP2ZcUrdOmi2Pj6g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wr3fcrdnazdx38df72fqe30r5af8yue54w7uzejw8gull8p2gefqsp2sh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MzdNVDAxdC9zNUNyc1RI
            aHpaZWp3V1hxUHY1WEpMS2NQWjVPczk2MGxZCkhKRGtvd0lqL1BXVlRaZFhGRGxl
            NVZZYWNNdnFYK0JmeHJSMUFpSU11MlEKLS0tIDNnYnJYaXE2S0QzQVQ0RytaNmF6
            Tnl2ZGV5c3ZrQjNOeHlmc3I5TGM3WWcKZf/4dvdJRgOd4Cmj0981wHOZQFxAvd7g
            Hxy5o+1tH4Cw77ktvDreA+/Bu0Gh1QlWXjUwrm96UTPn25hYTTD6BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-23T08:36:09Z"
    mac: ENC[AES256_GCM,data:mEg74wSRztidJeI/7W2oTcB+JY4notPIRuoBzQRSial99ZeCaYN1BG9xQygutlwNMpTqJ5Y1jlUQ6gOWxIqUYnaBYH4OI4WZLMCmU8uswU1KZid6+oOLvkYesgiYhRkgow0JY2Q2hhcuxZ3UKh2K7JmDoGieSBpnscIMQjYshlA=,iv:YS6hqhNB+R8AtkpFKcdgeJTb+LHMRqbrDfjiBaZ1Bs0=,tag:jhGCiCBT88Y20+tonseTfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
