---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  mame: starboard-operator
  namespace: starboard-system
spec:
  chart:
    spec:
      chart: aqua/starboard-operator
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: flux-system
      version: 0.10.3
  interval: 10m0s